# [theme]
# primaryColor="#F63366"
# backgroundColor="#FFFFFF"
# secondaryBackgroundColor="#F0F2F6"
# textColor="#1a2639"
# font="sans serif"

[theme]
primaryColor="#c24d2c" #red
backgroundColor="#FBFDFF" #lightblue
secondaryBackgroundColor="#fdffc6" # lightyellow
textColor="#000000" # black
font="sans serif"
baseFontSize = 18  

# https://www.shecodes.io/palettes/622

[logger]
level = "info"

